### ISSUE TITLE
 [zed2_imu_link] does not exist

### ISSUE THREAD

**Issue by NitroMajor** [fictionlab/erc_sim_ws#1]
No frame [zed2_imu_link] thus imu data can't be visualized and used properly.

**Comment by bjsowa** [comment]
The problem is that the [ZED ROS wrapper](https://github.com/stereolabs/zed-ros-wrapper) does not provide the `zed2_left_camera_frame -> zed2_imu_link` in their URDF because it is unique for each camera. Instead, it publishes the transform on the `zed2/left_cam_imu_transform` topic, which we also provide in the simulation.

I get that it can be a headache, so I added a node which takes a message from this topic and broadcasts the static transformation, so now the `zed2_imu_link` should be available. The same node will run on the real robot.

Let me know if it works for you now.

**Comment by NitroMajor** [comment]
Yeah, now works perfectly.
